version: "3.8"
services:
  app:
    image: "docker.io/jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - ./data/data:/data
      - ./data/letsencrypt:/etc/letsencrypt
  pocketbase:
    image: "localhost/stealid-pocketbase"
    ports:
      - "8080:8080"
    volumes:
      - ./data/pb_data:/pb/pb_data
  web:
    image: stealid-web
    build: ./stealid-web
    ports:
      - "4173:4173"
