version: "3.8"
networks:
  traefiknet: {}
services:
  reverse-proxy:
    image: traefik:v2.10
    networks:
      - traefiknet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./data/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  pocketbase:
    image: stealid-pocketbase
    build: ./stealid-pocketbase
    networks:
      - traefiknet
    volumes:
      - ./data/pb_data:/pb/pb_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pocketbase.entrypoints=web,websecure"
      - "traefik.http.routers.pocketbase.rule=Host(`${POCKET_BASE_URL}`) || (Host(`${WEB_URL}`) && PathPrefix(`/api`))"
      - "traefik.http.middlewares.rate-limiter.ratelimit.average=1000"
      - "traefik.http.middlewares.rate-limiter.ratelimit.period=1s"
      - "traefik.http.routers.pocketbase.middlewares=rate-limiter@docker"
  web:
    image: stealid-web
    build:
      context: ./stealid-web
      args:
        POCKET_BASE_URL: http://pocketbase:8080
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.svelte.entrypoints=web,websecure"
      - "traefik.http.routers.svelte.rule=Host(`${WEB_URL}`)"
      - "traefik.http.middlewares.front-limiter.ratelimit.average=100"
      - "traefik.http.middlewares.front-limiter.ratelimit.period=1s"
      - "traefik.http.routers.svelte.middlewares=front-limiter@docker"
    environment:
      - POCKET_BASE_URL=http://pocketbase:8080
