version: "3.8"
networks:
  traefiknet: {}
services:
  reverse-proxy:
    image: traefik:v2.10
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--certificatesresolvers.myresolver.acme.email="
      - "--certificatesresolvers.myresolver.acme.storage=acme.json"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
    networks:
      - traefiknet
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  pocketbase:
    image: stealid-pocketbase
    build: ./stealid-pocketbase
    networks:
      - traefiknet
    volumes:
      - ./data/pb_data:/pb/pb_data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pocketbase.rule=Host(`api.stealid.top`)"
      - "traefik.http.routers.pocketbase.entrypoints=web,websecure"
      - "traefik.http.routers.pocketbase.tls=true"
      - "traefik.http.routers.pocketbase.tls.certresolver=myresolver"
      - "traefik.http.middlewares.rate-limiter.ratelimit.average=1000"
      - "traefik.http.middlewares.rate-limiter.ratelimit.period=1s"
      - "traefik.http.routers.pocketbase.middlewares=rate-limiter@docker"
  web:
    image: stealid-web
    build: ./stealid-web
    networks:
      - traefiknet
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.svelte.rule=Host(`stealid.top`)"
      - "traefik.http.routers.svelte.entrypoints=web,websecure"
      - "traefik.http.routers.svelte.tls=true"
      - "traefik.http.routers.svelte.tls.certresolver=myresolver"
      - "traefik.http.middlewares.front-limiter.ratelimit.average=100"
      - "traefik.http.middlewares.front-limiter.ratelimit.period=1s"
      - "traefik.http.routers.svelte.middlewares=front-limiter@docker"
