version: "3.8"
services:
  pocketbase:
    image: "localhost/stealid-pocketbase"
    build: ./stealid-pocketbase
    ports:
      - "8080:8080"
    volumes:
      - ./data/pb_data:/pb/pb_data
  web:
    image: stealid-web
    build: ./stealid-web
    ports:
      - "4173:4173"
