version: "3.8"

services:
  reverse-proxy:
    volumes:
      - "./traefik.prod.yaml:/etc/traefik/traefik.yaml"
  pocketbase:
    labels:
      - "traefik.http.routers.pocketbase.tls=true"
      - "traefik.http.routers.pocketbase.tls.certresolver=myresolver"
  web:
    build:
      context: ./stealid-web
      args:
        POCKET_BASE_URL: https://${WEB_URL}
    labels:
      - "traefik.http.routers.svelte.tls=true"
      - "traefik.http.routers.svelte.tls.certresolver=myresolver"
    environment:
      - POCKET_BASE_URL=https://${WEB_URL}
