version: "3.8"
services:
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
  pocketbase:
    image: stealid-pocketbase
    build: ./stealid-pocketbase
    ports:
      - "8080:8080"
    volumes:
      - ./data/pb_data:/pb/pb_data
  web:
    image: stealid-web
    build: ./stealid-web
    ports:
      - "4173:4173"

volumes:
  caddy_data:
  caddy_config:
